# A list of devices you want to take the screenshots from
devices([
  "iPhone 8",
 # "iPhone SE",
 # "iPhone XS",
 # "iPhone XR",
])

languages([
  "es",
 # "de-DE",
 # "it-IT",
 # "ru"
])

# The name of the scheme which contains the UI Tests
scheme("Snapshots")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)
